pipeline:

  docker:
    image: plugins/docker
    storage_driver: vfs
    repo: omelhoro1/bab-la
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  deploy:
    image: drillster/drone-rsync
    user: captain
    hosts: [ "igor-fischer.rocks" ]
    port: 22
    target: /tmp/bab-la-${DRONE_COMMIT}/
    include:
      - "docker-compose.yml"
    exclude:
      - "**.*"
    delete: false
    secrets: [ rsync_key ]
    script:
      - docker-compose -f /tmp/bab-la-${DRONE_COMMIT}/docker-compose.yml pull
      - docker-compose -f /tmp/bab-la-${DRONE_COMMIT}/docker-compose.yml -p bab-la up -d
    when:
      branch: master
